version: '3.1'

services:
  reverseproxy:
    image: nginx:latest
    container_name: reverseproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/SSL/Td-team14.devsecops.fh-aachen.de.cer:/etc/nginx/SSL/Td-team14.devsecops.fh-aachen.de.cer
      - ./nginx/SSL/Td-team14.devsecops.fh-aachen.de.key:/etc/nginx/SSL/Td-team14.devsecops.fh-aachen.de.key

  threatdragon:
    image: owasp/threat-dragon:v2.0.9
    container_name: threatdragon
    depends_on:
       - reverseproxy
    expose:
      - "8080"
    volumes:
      - ./config.env:/app/.env

